version: 1
accounts:
  - name: user1
    coins: ["1000affondollar", "100000000stake"]
  - name: user2
    coins: ["1000affondollar", "100000000stake"]
validator:
  name: user1
  staked: "100000000stake"
