openapi: '3.0.0'
info:
  version: '1.0'
  title: NFT
servers:
  - url: http://192.168.1.160:1317
tags:
  - name: NFT
paths:
  /nft/denoms:
    get:
      summary: Get list of Denoms.
      tags:
      - NFT
      operationId: /nft/denoms
      responses:
        200:
          description: 成功時のレスポンス
  /nft/owner/{address}:
    get:
      summary: Get list of NFTs a specified owner have.
      description: Get list of NFTs a specified owner have.
      tags:
      - NFT
      operationId: getNftsByOwner
      parameters:
      - name: "address"
        description: 'An owner address'
        in: "path"
        required: true
        schema:
          type: string
          example: cosmos1gzfwesw9h0yp6pjr32ku4f3f28usezzarrqegh
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  height:
                    type: "integer"
                  result:
                    type: "object"
                    properties:
                      type:
                        type: "string"
                        example: "cosmos-sdk/Owner"
                      value:
                        type: "object"
                        properties:
                          address:
                            type: "string"
                            example: "COSMOS_ADDRESS"
                          idCollections:
                            type: array
                            nullable: true
                            items:
                              type: "object"
                              properties:
                                denom:
                                  type: "string"
                                  example: "DENOM_NAME"
                                ids:
                                  type: "array"
                                  items:
                                    type: "string"
                                    example: ["aaa", "bbb"]
  /nft/owners/collection/{denom}:
    get:
      summary: Get list of NFTs a specified owner have in a specified denom.
      description: Get list of NFTs a specified owner have in a specified denom.
      tags: 
      - Misc
      operationId: getNftsByOwnerAndDenom
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
  /nft/collection/{denom}:
    get:
      summary: Get list of NFTs in a specified denom.
      description: Get list of NFTs in a specified denom.
      tags:
      - Misc
      operationId: getNftsByDenom
      deprecated: false
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
  /nft/supply/{denom}:
    get:
      summary: Return total amount of tokens in a specified denom.
      tags:
      - Misc
      operationId: getSupplyByDenom
      deprecated: false
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
  /nfts/mint:
    post:
      summary: /nfts/mint
      tags:
      - Misc
      operationId: /nfts/mint
      deprecated: false
      parameters:
      - in: header
        name: Content-Type
        required: true
        schema:
          type: string
          example: "aaa"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/nfts/mintrequest'
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
  /nfts/transfer:
    post:
      summary: /nfts/transfer
      tags:
      - Misc
      operationId: /nfts/transfer
      deprecated: false
      parameters:
      - in: header
        name: Content-Type
        required: true
        schema:
          type: string
          example: "aaa"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/~1nfts~1transferrequest'
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
  /nfts/collection/crypto-kitties/nft/aaa/metadata:
    put:
      summary: /nfts/collection/crypto-kitties/nft/aaa/metadata
      tags:
      - Misc
      operationId: /nfts/collection/crypto-kitties/nft/aaa/metadata
      deprecated: false
      parameters:
      - in: header
        name: Content-Type
        required: true
        schema:
          type: string
          example: "aaa"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/nfts/collection/crypto-kitties/nft/aaa/metadata-request'
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
  /nfts/collection/crypto-kitties/nft/{nft-id}/burn:
    put:
      tags:
      - Misc
      operationId: Burn (delete) a specify NFT.
      parameters:
      - in: header
        name: Content-Type
        required: true
        schema:
          type: string
          example: "aaa"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/nfts/collection/crypto-kitties/nft/aaa/burn-request'
      responses:
        200:
          description: ''
          headers: {}
components:
  requestBodies:
    /nfts/mintrequest:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              base_req:
                $ref: '#/components/schemas/BaseReq'
              recipient:
                type: string
              denom:
                type: string
              id:
                type: string
              tokenURI:
                type: string
            required:
            - base_req
            - recipient
            - denom
            - id
            - tokenURI
          example:
            base_req:
              from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
              memo: "Sent from Postman \U0001F680"
              chain_id: voter
              account_number: 0
              sequence: 1
              gas: 200000
              gas_adjustment: 1.2
              fees:
              - denom: token
                amount: 50
              simulate: false
            recipient: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
            denom: MyToken
            id: aaa
            tokenURI: http://localhost:8080
    /nfts/transferrequest:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              base_req:
                $ref: '#/definitions/BaseReq'
              denom:
                type: string
              id:
                type: string
              recipient:
                type: string
            required:
            - base_req
            - denom
            - id
            - recipient
          example:
            base_req:
              from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
              memo: "Sent from Postman \U0001F680"
              chain_id: voter
              account_number: 0
              sequence: 1
              gas: 200000
              gas_adjustment: 1.2
              fees:
              - denom: token
                amount: 50
              simulate: false
            denom: MyToken
            id: aaa
            recipient: cosmos1atsc0j4w23derwmv98n72y28vdxsalp4zpcgz2
    /nfts/collection/crypto-kitties/nft/aaa/metadata-request:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              base_req:
                $ref: '#/definitions/BaseReq'
              denom:
                type: string
              id:
                type: string
              tokenURI:
                type: string
            required:
            - base_req
            - denom
            - id
            - tokenURI
          example:
            base_req:
              from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
              memo: "Sent from Postman \U0001F680"
              chain_id: voter
              account_number: 0
              sequence: 1
              gas: 200000
              gas_adjustment: 1.2
              fees:
              - denom: token
                amount: 50
              simulate: false
            denom: crypto-kitties
            id: aaa
            tokenURI: http://changeurl:8080
    /nfts/collection/crypto-kitties/nft/aaa/burn-request:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              base_req:
                $ref: '#/definitions/BaseReq'
              denom:
                type: string
              id:
                type: string
            required:
            - base_req
            - denom
            - id
          example:
            base_req:
              from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
              memo: "Sent from Postman \U0001F680"
              chain_id: voter
              account_number: 0
              sequence: 1
              gas: 200000
              gas_adjustment: 1.2
              fees:
              - denom: token
                amount: 50
              simulate: false
            denom: crypto-kitties
            id: aaa
  schemas:
    BaseReq:
      type: object
      properties:
        from:
          type: string
        memo:
          type: string
        chain_id:
          type: string
        account_number:
          type: string
        sequence:
          type: string
        gas:
          type: string
        gas_adjustment:
          type: string
        fees:
          type: array
          items:
            $ref: '#/definitions/Fee'
        simulate:
          type: boolean
      required:
      - from
      - memo
      - chain_id
      - account_number
      - sequence
      - gas
      - gas_adjustment
      - fees
      - simulate
      example:
        from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
        memo: "Sent from Postman \U0001F680"
        chain_id: voter
        account_number: 0
        sequence: 1
        gas: 200000
        gas_adjustment: 1.2
        fees:
        - denom: token
          amount: 50
        simulate: false
    Fee:
      type: object
      properties:
        denom:
          type: string
        amount:
          type: string
      required:
      - denom
      - amount
      example:
        denom: token
        amount: 50